# Generated by Django 5.0.6 on 2024-06-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0002_alter_cidades_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('altura', models.FloatField(default=0.0)),
                ('nascimento', models.DateField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cidades.cidades')),
            ],
        ),
    ]
